SELECT 
    COLUMN_NAME AS Column_Name,
    COLUMN_TYPE AS Data_Type,
    IS_NULLABLE AS Is_Nullable,
    COLUMN_DEFAULT AS Default_Value,
    COLUMN_KEY AS Key_Type,
    EXTRA AS Extra
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Books'
ORDER BY ORDINAL_POSITION;